### ISSUE TITLE
Fail Faster

### ISSUE THREAD

**Issue by caleb-james-smith** [BaylorCMS/gui-step1#2]
Quit earlier if there are I2C problems (say no QIE card or no backplane power).
Use sys.exit() with a helpful message.
Do not attempt to read temperature and perform Igloo test.

**Comment by bcmcms** [comment]
A proposed fix has been submitted in #7 avoiding sys.exit(). The reasoning was that restarting the GUI every time someone selects a slot without a card (possibly accidentally) could lead to problems.

**Comment by caleb-james-smith** [comment]
Yes, thanks. We don't want to restart the GUI for I2C_ERRORS.

**Comment by caleb-james-smith** [comment]
I can see the commit https://github.com/BaylorCMS/gui-step1/pull/7/commits/50da53718c119b05d7a8372118f259fe692972ee

**Comment by caleb-james-smith** [comment]
But I don't see that change in the merge, which is weird: https://github.com/BaylorCMS/gui-step1/pull/7/files

**Comment by bcmcms** [comment]
That's because it had a merge conflict with a fix you already pulled into master. Rather than revert your work, I removed my edits.

**Comment by caleb-james-smith** [comment]
Great. We will close this.
