### ISSUE TITLE
HB Igloo Programming through ngCCM Emulator

### ISSUE THREAD

**Issue by caleb-james-smith** [BaylorCMS/gui-step1#20]
- Add ability to program HB Igloos (top and bottom) via ngCCM Emulator.
- Make buttons for programming either top or bottom igloo.
- Make all I2C communication complete full multiplexing for each command. Use full chain every time and remove dependence on previous multiplexing.

**Comment by cmshcal11** [comment]
Note that self.address is hard-coded to be 0x19 right now. This could be fixed with the full multiplexing issue...

**Comment by caleb-james-smith** [comment]
In this pull request: https://github.com/FNAL-HCAL-Ph1Upgrade/gui-step1/pull/21
- we can program top or bottom igloo
- we have added more robust multiplexing

**Comment by caleb-james-smith** [comment]
The remaining task is to make a button for programming top and bottom igloo.
The top and bottom igloo have different JTAG select values (0 for top and 1 for bottom).
Thus we need a button (or dropdown menu) to select top or bottom igloo.

**Comment by caleb-james-smith** [comment]
Here is the relevant section that sets up Igloo programming: https://github.com/FNAL-HCAL-Ph1Upgrade/gui-step1/blob/HB_Master/User-Interface.py#L1225-L1241

**Comment by caleb-james-smith** [comment]
We now have a script that runs on the Windows PC. It programs HB QIE cards and uploads the firmware versions and programming pass/fail to the database.
https://github.com/FNAL-HCAL-Ph1Upgrade/gui-step1/pull/28

**Comment by caleb-james-smith** [comment]
Here is the release: https://github.com/FNAL-HCAL-Ph1Upgrade/gui-step1/releases/tag/HB_2.0
