### ISSUE TITLE
Check Checksum

### ISSUE THREAD

**Issue by caleb-james-smith** [BaylorCMS/gui-step1#3]
Verify Unique ID checksum after reading.
Add as test to database.
This will ensure that we read UniqueIDs correctly before they are uploaded to the database.

**Comment by bcmcms** [comment]
The test should be in and working on the GUI side.

**Comment by caleb-james-smith** [comment]
Can we add a GUI box that displays the result of the test (say pass/fail or true/false) to the user?

**Comment by bcmcms** [comment]
There already is in my PR.

**Comment by caleb-james-smith** [comment]
https://github.com/BaylorCMS/gui-step1/pull/17

**Comment by caleb-james-smith** [comment]
Great. Merged.
